services:
  nginx:
    image: nginx:alpine
    container_name: visual_patrol_nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/frontend:/app/frontend:ro
    restart: unless-stopped

  robot-a:
    container_name: visual_patrol_robot_a
    build: .
    network_mode: host
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - TZ=Asia/Taipei
      - PORT=5001
      - ROBOT_ID=robot-a
      - ROBOT_NAME=Robot A
      - ROBOT_IP=192.168.50.133:26400
    restart: unless-stopped

  robot-b:
    container_name: visual_patrol_robot_b
    build: .
    network_mode: host
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - TZ=Asia/Taipei
      - PORT=5002
      - ROBOT_ID=robot-b
      - ROBOT_NAME=Robot B
      - ROBOT_IP=192.168.50.133:26400
    restart: unless-stopped

  robot-c:
    container_name: visual_patrol_robot_c
    build: .
    network_mode: host
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - TZ=Asia/Taipei
      - PORT=5003
      - ROBOT_ID=robot-c
      - ROBOT_NAME=Robot C
      - ROBOT_IP=192.168.50.133:26400
    restart: unless-stopped
